/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "eeprom.h"
#include "uart.h"
#include "led.h"
#include "i2c.h"

/*void mymenu(int ch)
{
	switch(ch)
	{

		case 1:
			LedBlink(LED_GREEN, 500);
			EEPROM_Write(0x0020, (uint8_t*)"GOD BLESS YOU!\r\n", 16);
			break;

		case 3:
			LedBlink(LED_BLUE, 500);
			EEPROM_Read(0x0020, (uint8_t*)str, 16);
			break;



	}
}*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	char strch[16];
		int ch=0;
		LedInit(LED_GREEN);
			LedInit(LED_RED);
			LedInit(LED_BLUE);
	SystemInit();
	EEPROM_Init();
	UartInit(BAUD_9600);
	char str[32] = "";


		while(1) {
			UartPuts("\r Choose action\n");
				UartPuts("\r 1. Write \n\r 2. Read \n\r ");
				UartGets(strch);

				sscanf(strch, "%d", &ch);
				UartPuts("\r choice done \n\r ");
				//mymenu(ch);

				switch(ch)
					{

						case 1:
							LedBlink(LED_GREEN, 500);
							UartPuts("\r Give a string ");
							UartGets(str);
							EEPROM_Write(0x0000, (uint8_t*)str, 16);
							break;

						case 2:
							LedBlink(LED_BLUE, 500);
							EEPROM_Read(0x0000, (uint8_t*)str,32);
							UartPuts(str);
							break;


			}

	//while(1);
				}
	return 0;
}









